#include "osdev/input/keycode.h"
#include "osdev/input/keyboard.h"
#include "driver/keyboard.h"
#include "arch/irq.h"
#include "kstdlib.h"
#include "arch/port.h"

static const uint32_t KEYBOARD_IRQ = 1;
static const uint8_t DATA_PORT = 0x60;

static uint16_t keymap[256] = {
/* 00 */  KEY_RESERVED, KEY_ESC,       KEY_1,         KEY_2,         KEY_3,         KEY_4,        KEY_5,         KEY_6,
/* 08 */  KEY_7,        KEY_8,         KEY_9,         KEY_0,         KEY_MINUS,     KEY_EQUAL,    KEY_BACKSPACE, KEY_TAB,
/* 10 */  KEY_Q,        KEY_W,         KEY_E,         KEY_R,         KEY_T,         KEY_Y,        KEY_U,         KEY_I,
/* 18 */  KEY_O,        KEY_P,         KEY_LEFTBRACE, KEY_RIGHTBRACE,KEY_ENTER,     KEY_LEFTCTRL, KEY_A,         KEY_S,
/* 20 */  KEY_D,        KEY_F,         KEY_G,         KEY_H,         KEY_J,         KEY_K,        KEY_L,         KEY_SEMICOLON,
/* 28 */  KEY_APOSTROPHE,KEY_GRAVE,    KEY_LEFTSHIFT, KEY_BACKSLASH, KEY_Z,         KEY_X,        KEY_C,         KEY_V,
/* 30 */  KEY_B,        KEY_N,         KEY_M,         KEY_COMMA,     KEY_DOT,       KEY_SLASH,    KEY_RIGHTSHIFT,KEY_KPASTERISK, 
/* 38 */  KEY_LEFTALT,  KEY_SPACE,     KEY_CAPSLOCK,  KEY_F1,        KEY_F2,        KEY_F3,       KEY_F4,        KEY_F5,
/* 40 */  KEY_F6,       KEY_F7,        KEY_F8,        KEY_F9,        KEY_F10,       KEY_NUMLOCK,  KEY_SCROLLLOCK,KEY_KP7,
/* 48 */  KEY_KP8,      KEY_KP9,       KEY_KPMINUS,   KEY_KP4,       KEY_KP5,       KEY_KP6,      KEY_KPPLUS,    KEY_KP1,
/* 50 */  KEY_KP2,      KEY_KP3,       KEY_KP0,       KEY_KPDOT,     KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_F11,
/* 58 */  KEY_F12,      KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 60 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 68 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 70 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 78 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 80 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 88 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 90 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 98 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* a0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* a8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* b0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* b8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* c0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* c8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* d0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* d8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* e0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* e8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* f0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* f8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED};

/* keymap for 0xe0 scan sequence */
uint16_t keymap_ext[256] = {
/*              00          01             02             03               04             05             06           07     */    
/* 00 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 08 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 10 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 18 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_KPENTER,   KEY_RIGHTCTRL,KEY_RESERVED,  KEY_RESERVED,
/* 20 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 28 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 30 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_KPSLASH,  KEY_RESERVED,  KEY_RESERVED,
/* 38 */  KEY_RIGHTALT, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 40 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_HOME,
/* 48 */  KEY_UP,       KEY_PAGEUP,    KEY_RESERVED,  KEY_LEFT,      KEY_RESERVED,  KEY_RIGHT,    KEY_RESERVED,  KEY_END,
/* 50 */  KEY_DOWN,     KEY_PAGEDOWN,  KEY_INSERT,    KEY_DELETE,    KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 58 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 60 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 68 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 70 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 88 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 80 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 88 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 90 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* 98 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* a0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* a8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* b0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* b8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* c0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* c8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* d0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* d8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* e0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* e8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* f0 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,
/* f8 */  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,  KEY_RESERVED 
};

static kbd_handler_func handler = 0;
void keyboard_register(kbd_handler_func func)
{
    handler = func;
}


static uint16_t update_modifier(uint16_t modifiers, uint8_t keycode, bool up)
{
    uint8_t modifier = 0;
    uint16_t newmodifiers = modifiers;

    /* 
     * update LOCK modifier 
     * toggle the bit if DOWN (ONLY care about DOWN)
     */
    if (keycode == KEY_CAPSLOCK && !up)
    {
        newmodifiers ^= KEY_MOD_CAPSLOCK;
        return newmodifiers;
    }
    else if (keycode == KEY_NUMLOCK && !up)
    {
        newmodifiers ^= KEY_MOD_NUMLOCK;
        return newmodifiers;
    }

    /* 
     * update shift/ctrl/alt modifier
     * set bit if UP and clear bit if DOWN
     */
    switch (keycode)
    {
        case KEY_LEFTCTRL:
            modifier = KEY_MOD_LCTRL;
            break;
        case KEY_RIGHTCTRL:
            modifier = KEY_MOD_RCTRL;
            break;
        case KEY_LEFTALT:
            modifier = KEY_MOD_LALT;
            break;
        case KEY_RIGHTALT:
            modifier = KEY_MOD_RALT;
            break;
        case KEY_LEFTSHIFT:
            modifier = KEY_MOD_LSHIFT;
            break;
        case KEY_RIGHTSHIFT:
            modifier = KEY_MOD_RSHIFT;
            break;
        default:
            break;
    } 

    if (modifier != 0) // modifier hit
    {
        if (up) 
            newmodifiers &= ~modifier;
        else 
            newmodifiers |= modifier;
    }

    return newmodifiers;
}
static bool ext_sequence = false;
static uint16_t modifiers = 0; /* state for modifiers */
static void keyboard_isr(struct regs regs)
{
    (void)regs;
    uint8_t scancode = inb(DATA_PORT);

    if (scancode != 0xE0) {
        bool up = scancode & 0x80;
        scancode = scancode & (~0x80); /* strip off the up/down flag */
        uint8_t keycode = ext_sequence ? keymap_ext[scancode] : keymap[scancode];
        modifiers = update_modifier(modifiers, scancode, up);

        key_event_t event = {
            .keycode = keycode,
            .modifiers = modifiers,
            .action = up ? KEY_ACT_UP : KEY_ACT_DOWN
        };

        if (handler) 
            handler(event);
        
        ext_sequence = false;
    }
    else {
        ext_sequence = true;
    } 
}

void keyboard_init()
{
    irq_register(KEYBOARD_IRQ, &keyboard_isr);
}